export const contentData = {
  GK: [
    // --- INDIAN POLITY & CONSTITUTION ---
    { id: "gk_in_1", question: "Which Article of the Indian Constitution provides for the 'Right to Education' as a Fundamental Right?", options: ["Article 19", "Article 21A", "Article 14", "Article 32"], answer: "Article 21A", explanation: "The 86th Constitutional Amendment Act, 2002 inserted Article 21A." },
    { id: "gk_in_2", question: "What does 'Guillotine' mean in the Indian Parliament context?", options: ["Vote of no-confidence", "Adjournment", "Voting undiscussed demands for grants", "Moving a motion"], answer: "Voting undiscussed demands for grants", explanation: "Guillotine is used to fast-track the budget passing process." },
    { id: "gk_in_3", question: "Which committee recommended the 3-tier Panchayati Raj system?", options: ["Ashok Mehta", "Balwant Rai Mehta", "G.V.K. Rao", "L.M. Singhvi"], answer: "Balwant Rai Mehta", explanation: "Recommended in 1957; the basis for India's local self-government." },
    { id: "gk_in_4", question: "The Fifth Schedule of the Indian Constitution deals with?", options: ["State allocations", "Scheduled Areas & Tribes", "Tribal Areas in NE", "Official Languages"], answer: "Scheduled Areas & Tribes", explanation: "Provides for administration of Tribal areas except in Assam, Meghalaya, Tripura, Mizoram." },
    { id: "gk_in_5", question: "How many Fundamental Duties are currently in the Indian Constitution?", options: ["10", "11", "12", "9"], answer: "11", explanation: "The 11th duty was added by the 86th Amendment Act in 2002." },

    // --- INDIAN HISTORY ---
    { id: "gk_hi_1", question: "Jahangir permitted the first English factory in which city?", options: ["Calcutta", "Madras", "Surat", "Bombay"], answer: "Surat", explanation: "Surat was the first site of an English factory in India in 1613." },
    { id: "gk_hi_2", question: "Which Viceroy issued the 'Deepavali Declaration' in 1929?", options: ["Lord Chelmsford", "Lord Irwin", "Lord Reading", "Lord Curzon"], answer: "Lord Irwin", explanation: "Announced Dominion Status as the ultimate goal for India." },
    { id: "gk_hi_3", question: "Founder of the Satavahana dynasty?", options: ["Simo-Shuka", "Gautamiputra", "Satakarni", "Pulakeshin"], answer: "Simo-Shuka", explanation: "Simuka (or Simu-shuka) founded the dynasty in the 1st century BC." },
    { id: "gk_hi_4", question: "The 'Permanent Settlement' (1793) was introduced by?", options: ["Warren Hastings", "Lord Cornwallis", "Lord Wellesley", "Lord Dalhousie"], answer: "Lord Cornwallis", explanation: "It was a land revenue system introduced in Bengal." },
    { id: "gk_hi_5", question: "Who was the founder of the Indian National Social Conference?", options: ["MG Ranade", "Gopal Ganesh Agarkar", "Annie Besant", "Keshab Chandra Sen"], answer: "MG Ranade", explanation: "Founded in 1887 to focus on social reforms." },

    // --- WORLD GEOGRAPHY ---
    { id: "gk_ge_1", question: "Highest peak in Western Ghats?", options: ["Doddabetta", "Anamudi", "Kalsubai", "Mezapulimala"], answer: "Anamudi", explanation: "Located in Eravikulam National Park, Kerala (2,695m)." },
    { id: "gk_ge_2", question: "Which canal connects Suez and the Mediterranean?", options: ["Kiel Canal", "Suez Canal", "Panama Canal", "Corinth Canal"], answer: "Suez Canal", explanation: "Links the Mediterranean Sea to the Red Sea." },
    { id: "gk_ge_3", question: "Which country has the largest number of active volcanoes?", options: ["Japan", "USA", "Indonesia", "Iceland"], answer: "Indonesia", explanation: "Indonesia lies on the Pacific Ring of Fire and has over 120 active volcanoes." },
    { id: "gk_ge_4", question: "What is the 'Albedo Effect'?", options: ["Heat absorption", "Solar radiation reflection", "Ocean currents", "Atmospheric pressure"], answer: "Solar radiation reflection", explanation: "Albedo is the fraction of solar energy reflected from the Earth back into space." },
    { id: "gk_ge_5", question: "The 'Roaring Forties' are found in which ocean?", options: ["North Atlantic", "South Pacific", "Southern Ocean", "Arctic Ocean"], answer: "Southern Ocean", explanation: "Strong westerly winds between 40-50 degrees latitude." },

    // --- SCIENCE & TECH ---
    { id: "gk_sc_1", question: "Escape velocity of Earth?", options: ["7.2 km/s", "11.2 km/s", "15.5 km/s", "9.8 km/s"], answer: "11.2 km/s", explanation: "Minimum speed needed to break free from gravitational pull." },
    { id: "gk_sc_2", question: "Vitamin synthesized by skin?", options: ["Vitamin C", "Vitamin K", "Vitamin A", "Vitamin D"], answer: "Vitamin D", explanation: " Sunlight helps skin produce cholecalciferol (D3)." },
    { id: "gk_sc_3", question: "A light year measures?", options: ["Time", "Distance", "Brightness", "Speed"], answer: "Distance", explanation: "The distance light travels in one year (approx 9.46 trillion km)." },
    { id: "gk_sc_4", question: "Which part of the brain controls body temperature?", options: ["Cerebrum", "Cerebellum", "Hypothalamus", "Medulla"], answer: "Hypothalamus", explanation: "Hypothalamus acts as the body's thermostat." },
    { id: "gk_sc_5", question: "Study of Fossils is known as?", options: ["Archaeology", "Paleontology", "Geology", "Anthropology"], answer: "Paleontology", explanation: "Scientific study of life that existed prior to or during the Holocene epoch." },

    // --- CURRENT AFFAIRS & SPORTS ---
    { id: "gk_ca_1", question: "G20 Summit 2023 host?", options: ["India", "Italy", "Indonesia", "Brazil"], answer: "India", explanation: "Theme was 'One Earth, One Family, One Future'." },
    { id: "gk_ca_2", question: "2023 Nobel Peace Prize winner?", options: ["Narges Mohammadi", "Malala", "Greta", "Maria Ressa"], answer: "Narges Mohammadi", explanation: "Honored for her fight against female oppression in Iran." },
    { id: "gk_ca_3", question: "Country which joined NATO in 2023?", options: ["Ukraine", "Sweden", "Finland", "Georgia"], answer: "Finland", explanation: "Became the 31st member on April 4, 2023." },
    { id: "gk_ca_4", question: "Who won the men's singles at Wimbledon 2023?", options: ["Novak Djokovic", "Carlos Alcaraz", "Daniil Medvedev", "Jannik Sinner"], answer: "Carlos Alcaraz", explanation: "Defeated Novak Djokovic in a historic 5-set final." },
    { id: "gk_ca_5", question: "Name of the lunar lander for Chandrayaan-3?", options: ["Pragyan", "Vikram", "Dhruv", "Siddharth"], answer: "Vikram", explanation: "The lander was named Vikram, after Vikram Sarabhai." },

    // --- ART, CULTURE & MISC (Tough level) ---
    { id: "gk_ac_1", question: "The 'Kalamkari' paint style belongs to?", options: ["Andhra Pradesh", "Tamil Nadu", "Rajasthan", "Karnataka"], answer: "Andhra Pradesh", explanation: "Hand-painted or block-printed cotton textile produced in Masulipatnam." },
    { id: "gk_ac_2", question: "Who composed the 'Suryashtakam'?", options: ["Kalidasa", "Samba", "Adi Sankara", "Valmiki"], answer: "Samba", explanation: "According to Puranas, Samba (Krishna's son) built the Multan Sun temple and composed it." },
    { id: "gk_ac_3", question: "The 'Hornbill Festival' is celebrated in?", options: ["Assam", "Nagaland", "Manipur", "Arunachal"], answer: "Nagaland", explanation: "Known as the 'festival of festivals', held every December." },
    { id: "gk_ac_4", question: "First Indian to win an Oscar?", options: ["Bhanu Athaiya", "Satyajit Ray", "AR Rahman", "Resul Pookutty"], answer: "Bhanu Athaiya", explanation: "Won for Costume Design in the 1982 film 'Gandhi'." },
    { id: "gk_ac_5", question: "Largest brackish water lagoon in India?", options: ["Vembanad", "Pulicat", "Chilika", "Kolleru"], answer: "Chilika", explanation: "Located in Odisha, India's largest coastal lagoon." },

    // --- WORLD HISTORY ---
    { id: "gk_wh_1", question: "Leader of the French Revolution?", options: ["Napoleon", "Robespierre", "Louis XVI", "Voltaire"], answer: "Robespierre", explanation: "Key figure during the 'Reign of Terror'." },
    { id: "gk_wh_2", question: "Magna Carta was signed in which year?", options: ["1215", "1066", "1381", "1492"], answer: "1215", explanation: "King John of England signed the Charter of Liberties." },
    { id: "gk_wh_3", question: "The 'Industrial Revolution' began in?", options: ["France", "Germany", "Great Britain", "USA"], answer: "Great Britain", explanation: "Around 1760, transitioning to new manufacturing processes." },
    { id: "gk_wh_4", question: "Who was known as the 'Desert Fox' in WWII?", options: ["Montgomery", "Rommel", "Patton", "Eisenhower"], answer: "Rommel", explanation: "Erwin Rommel was a highly decorated field marshal in Nazi Germany." },
    { id: "gk_wh_5", question: "First woman in space?", options: ["Sally Ride", "Valentina Tereshkova", "Sunita Williams", "Kalpana Chawla"], answer: "Valentina Tereshkova", explanation: "Soviet cosmonaut on Vostok 6 in 1963." },

    // --- ECONOMY ---
    { id: "gk_ec_1", question: "What is 'Stagflation'?", options: ["Inflation + Growth", "Deflation + Growth", "Inflation + Unemployment", "Price stability"], answer: "Inflation + Unemployment", explanation: "A situation of stagnant growth combined with high inflation." },
    { id: "gk_ec_2", question: "RBI was nationalized in?", options: ["1935", "1947", "1949", "1955"], answer: "1949", explanation: "Established in 1935, nationalized after independence." },
    { id: "gk_ec_3", question: "Gresham's Law states that?", options: ["Cheap money drives out dear money", "Supply creates its own demand", "Bad money drives out good", "Demand creates its own supply"], answer: "Bad money drives out good", explanation: "If two currencies are in circulation, the less valuable one will displace the more valuable one." },
    { id: "gk_ec_4", question: "Headquarters of WTO?", options: ["Paris", "Washington", "Geneva", "Brussels"], answer: "Geneva", explanation: "World Trade Organization, located in Switzerland." },
    { id: "gk_ec_5", question: "The term BULL and BEAR are associated with?", options: ["Agriculture", "Space", "Stock Market", "Forestry"], answer: "Stock Market", explanation: "Bulls expect prices to rise; Bears expect them to fall." }
  ],

  Reasoning: [
    { id: "re_1", question: "A counts 40 students. R is 11th from right. Position from left?", options: ["29", "30", "31", "32"], answer: "30", explanation: "Step 1: Total students (N) = 40. Step 2: Position from right (R) = 11. Step 3: Formula: Position from Left (L) = (N - R) + 1. Step 4: L = (40 - 11) + 1 = 29 + 1 = 30." },
    { id: "re_2", question: "Sequence: 7, 26, 63, 124, 215, ?", options: ["342", "343", "441", "512"], answer: "342", explanation: "Step 1: Observe the cubes of numbers: 2^3=8, 3^3=27, 4^3=64, 5^3=125, 6^3=216. Step 2: Notice each term is (n^3 - 1). Step 3: The next term is 7^3 - 1. Step 4: 7*7*7 = 343. Step 5: 343 - 1 = 342." },
    { id: "re_3", question: "If 'A' is '+', 'B' is '-', 'C' is '*', find 10C5A3B2.", options: ["51", "53", "48", "45"], answer: "51", explanation: "Step 1: Substitute letters with symbols: 10 * 5 + 3 - 2. Step 2: Apply BODMAS (Multiplication first): 10 * 5 = 50. Step 3: Addition: 50 + 3 = 53. Step 4: Subtraction: 53 - 2 = 51." },
    { id: "re_4", question: "Find missing: 1, 3, 7, 15, 31, ?", options: ["62", "63", "64", "65"], answer: "63", explanation: "Step 1: Find the difference between consecutive terms: 2, 4, 8, 16. Step 2: Notice the difference doubles each time. Step 3: Next difference = 16 * 2 = 32. Step 4: Next term = 31 + 32 = 63." },
    { id: "re_5", question: "Which is the odd one?", options: ["35", "49", "63", "81"], answer: "81", explanation: "Step 1: Check if numbers are multiples of 7: 35, 49, 63 are all multiples. Step 2: Check for other properties: 81 is a perfect square (9*9) while others are not squares of an integer except 49. Step 3: Wait, 49 is also a square. Step 4: Primary property: 35, 49, 63 are multiples of 7. 81 is not." },
    { id: "re_6", question: "B is South-West of A. C is East of B and South-East of A. D is North of C in line with B and A. D direction from A?", options: ["North", "East", "North-East", "South-East"], answer: "North-East", explanation: "Step 1: Draw the directions. A is at center. B at (-1, -1). C at (+1, -1). Step 2: D is North of C, so x=+1. Step 3: D is in line with A(0,0) and B(-1,-1). Line AB has equation y=x. Step 4: For D, x=+1, so y=+1. Step 5: (1, 1) is North-East from A." },
    { id: "re_7", question: "Statement: All mangoes are golden. No golden things are cheap. Conclusion: I. All mangoes are cheap. II. Golden mangoes are not cheap.", options: ["Only I", "Only II", "Both", "Neither"], answer: "Only II", explanation: "Step 1: Mangoes ⊂ Golden. Step 2: Golden ∩ Cheap = ∅. Step 3: Therefore, Mangoes ∩ Cheap = ∅. Step 4: Conclusion II is valid (Golden mangoes are just mangoes, and they are not cheap)." },
    { id: "re_8", question: "Clock shows 4:30. Hour hand points South-West. Minutes hand direction?", options: ["North", "East", "West", "South"], answer: "South", explanation: "Step 1: At 4:30, minute hand is at 6 (exactly vertical down). Step 2: Vertical down is South in standard clock orientation. Step 3: Even if orientation is rotated, minute hand at '6' still represents the 'South' cardinal direction in most logic puzzles." },
    { id: "re_9", question: "Pointing to Ravi, Sarit said, 'His father is the only son of my grandfather'. Relation?", options: ["Brother", "Cousin", "Father", "Maternal Uncle"], answer: "Brother", explanation: "Step 1: Sarit's grandfather's only son = Sarit's father. Step 2: Ravi's father = Sarit's father. Step 3: Therefore, Ravi and Sarit are siblings." },
    { id: "re_10", question: "Code: BRAZIL = 2-18-1-26-9-12. Code: INDIA = ?", options: ["9-14-4-9-1", "8-13-3-8-1", "10-15-5-10-2", "9-13-4-8-1"], answer: "9-14-4-9-1", explanation: "Step 1: Map letters to positions (A=1, B=2...). Step 2: I=9, N=14, D=4, I=9, A=1. Step 3: 9-14-4-9-1." },
    { id: "re_11", question: "If 1st Jan 2007 was Monday. 1st Jan 2008?", options: ["Monday", "Tuesday", "Wednesday", "Sunday"], answer: "Tuesday", explanation: "Step 1: 2007 is a non-leap year (365 days). Step 2: 365 days has 1 odd day (365/7 = 52 weeks + 1 day). Step 3: Move forward by 1 day from Monday. Step 4: Result is Tuesday." },
    { id: "re_12", question: "Mirror image of TIME? (Clock)", options: ["EMI-T", "EMIT", "3MIT", "MI-ET"], answer: "EMIT", explanation: "Step 1: In a mirror, left becomes right. Step 2: T becomes the rightmost, E becomes the leftmost. Step 3: Letters themselves also flip horizontally. Step 4: EMIT is the closest approximation." },
    { id: "re_13", question: "Missing in 4, 9, 25, 49, 121, ?", options: ["144", "169", "196", "225"], answer: "169", explanation: "Step 1: Numbers are 2^2, 3^2, 5^2, 7^2, 11^2. Step 2: Notice the bases: 2, 3, 5, 7, 11 are prime numbers. Step 3: Next prime is 13. Step 4: 13^2 = 169." },
    { id: "re_14", question: "A is faster than B. B and C are equally fast. C is slower than D. Who is slowest?", options: ["A", "B", "D", "B & C Both"], answer: "B & C Both", explanation: "Step 1: A > B. Step 2: B = C. Step 3: D > C. Step 4: Since B and C are equal and both are slower than A and D, B and C are the slowest." },
    { id: "re_15", question: "Syllogism: All books are pens. No pen is a copy. Conclusion: I. No book is copy. II. Some pens are books.", options: ["Only I", "Only II", "Both", "Neither"], answer: "Both", explanation: "Step 1: Books ⊂ Pens. Step 2: Pens ∩ Copies = ∅. Step 3: Therefore Books ∩ Copies = ∅ (I follows). Step 4: If Books ⊂ Pens, then at least some Pens are Books (II follows)." },
    { id: "re_16", question: "Find the missing: ACE, GIK, MOQ, ?", options: ["STU", "SUW", "RTV", "QRS"], answer: "SUW", explanation: "Step 1: A(+2)C(+2)E. Step 2: G(+2)I(+2)K. Step 3: M(+2)O(+2)Q. Step 4: Notice gap between E-G (+2), K-M (+2). Step 5: Start next at Q+2 = S. Step 6: S(+2)U(+2)W." },
    { id: "re_17", question: "If 'WATER' is coded as 'XBUFS', then 'LAKE'?", options: ["MBFL", "KBJD", "MCKG", "MBLF"], answer: "MBFL", explanation: "Step 1: W+1=X, A+1=B, T+1=U, E+1=F, R+1=S. Step 2: Apply to LAKE: L+1=M, A+1=B, K+1=L, E+1=F. Result: MBFL." },
    { id: "re_18", question: "Number of triangles in a Square with two diagonals and one horizontal cut through center?", options: ["8", "12", "16", "20"], answer: "12", explanation: "Step 1: 8 small triangles from diagonals/mid-cut. Step 2: 4 larger triangles formed by combining 2 adjacent small ones. Total = 8+4 = 12." },
    { id: "re_19", question: "Odd one: Gold, Silver, Coal, Copper?", options: ["Gold", "Silver", "Coal", "Copper"], answer: "Coal", explanation: "Step 1: Gold, Silver, Copper are metallic elements. Step 2: Coal is a sedimentary rock / fossil fuel. Step 3: Coal is the odd one." },
    { id: "re_20", question: "If 5*4=20, 3*2=6, 8*5=?", options: ["40", "13", "3", "32"], answer: "40", explanation: "Step 1: Pattern is simple multiplication. 5*4=20, 3*2=6. Step 2: 8*5 = 40." }
  ],

  Maths: [
    { id: "ma_1", question: "Value of log10(100)?", options: ["1", "2", "10", "100"], answer: "2", explanation: "Step 1: log10(100) asks '10 to what power equals 100?'. Step 2: 10 * 10 = 100. Step 3: So 10^2 = 100. Answer = 2." },
    { id: "ma_2", question: "Area of triangle sides 3, 4, 5?", options: ["6", "10", "12", "7"], answer: "6", explanation: "Step 1: Sides 3, 4, 5 form a right-angled triangle (3^2+4^2=5^2). Step 2: Area = 1/2 * base * height. Step 3: Area = 1/2 * 3 * 4. Step 4: 12 / 2 = 6." },
    { id: "ma_3", question: "Probability of picking a King from 52 cards?", options: ["1/13", "1/52", "4/13", "1/4"], answer: "1/13", explanation: "Step 1: Total Kings in a deck = 4. Step 2: Total cards = 52. Step 3: Probability = Favorable / Total. Step 4: 4/52 simplifies to 1/13." },
    { id: "ma_4", question: "Diff between SI and CI on 1000 for 2 yrs at 10%?", options: ["5", "10", "15", "20"], answer: "10", explanation: "Step 1: SI = (1000 * 10 * 2) / 100 = 200. Step 2: CI = P(1+R/100)^n - P = 1000(1.1)^2 - 1000 = 1210 - 1000 = 210. Step 3: Difference = 210 - 200 = 10." },
    { id: "ma_5", question: "tan θ = 3/4, then sin θ?", options: ["3/5", "4/5", "1", "3/4"], answer: "3/5", explanation: "Step 1: tan θ = Perpendicular / Base = 3 / 4. Step 2: Hypotenuse = √(3^2 + 4^2) = √25 = 5. Step 3: sin θ = Perpendicular / Hypotenuse = 3 / 5." },
    { id: "ma_6", question: "0.33... in fraction?", options: ["1/3", "1/2", "3/10", "3/33"], answer: "1/3", explanation: "Step 1: Let x = 0.333... Step 2: 10x = 3.333... Step 3: Subtract: 10x - x = 3.333 - 0.333. Step 4: 9x = 3. Step 5: x = 3/9 = 1/3." },
    { id: "ma_7", question: "Speed 72 km/hr in m/s?", options: ["15", "20", "25", "30"], answer: "20", explanation: "Step 1: To convert km/hr to m/s, multiply by 5/18. Step 2: 72 * (5/18). Step 3: 72 / 18 = 4. Step 4: 4 * 5 = 20." },
    { id: "ma_8", question: "Simple interest 1/16 of principal. Rate = years. Rate is?", options: ["2.5%", "3%", "4%", "5%"], answer: "2.5%", explanation: "Step 1: PRT/100 = P/16. Step 2: (P*R*R)/100 = P/16. Step 3: R^2 = 100/16. Step 4: R = √(100/16) = 10/4 = 2.5." },
    { id: "ma_9", question: "3 men or 5 women do work in 12 days. 6 men and 5 women do it in?", options: ["4 days", "5 days", "6 days", "8 days"], answer: "4 days", explanation: "Step 1: Efficiency of 3m = 5w. Step 2: 6m = 10w. Step 3: 6m + 5w = 15w. Step 4: 5w do it in 12 days, so 15w do it in (5/15) * 12 = 4 days." },
    { id: "ma_10", question: "Sum of first 50 natural numbers?", options: ["1225", "1250", "1275", "1300"], answer: "1275", explanation: "Step 1: Formula: n(n+1)/2. Step 2: 50 * 51 / 2. Step 3: 25 * 51 = 1275." },
    { id: "ma_11", question: "Volume of sphere radius 3?", options: ["36π", "27π", "12π", "18π"], answer: "36π", explanation: "Step 1: Formula: 4/3 * π * r^3. Step 2: 4/3 * π * 3^3 = 4/3 * π * 27. Step 3: 4 * 9 * π = 36π." },
    { id: "ma_12", question: "Average of first 10 prime numbers?", options: ["10.4", "11.2", "12.9", "13.1"], answer: "12.9", explanation: "Step 1: Primes are 2, 3, 5, 7, 11, 13, 17, 19, 23, 29. Step 2: Sum = 129. Step 3: Average = 129 / 10 = 12.9." },
    { id: "ma_13", question: "Solve for x: sqrt(x) + sqrt(x-5) = 5", options: ["6", "9", "4", "2"], answer: "9", explanation: "Step 1: Plug in options or solve. Let x=9. Step 2: √9 + √(9-5) = 3 + √4. Step 3: 3 + 2 = 5. Step 4: Correct." },
    { id: "ma_14", question: "A can do job in 10 days, B in 15 days. Together?", options: ["5", "6", "7", "8"], answer: "6", explanation: "Step 1: Work rate A = 1/10 per day. Step 2: Work rate B = 1/15 per day. Step 3: Combined = 1/10 + 1/15 = 5/30 = 1/6. Step 4: Total days = 6." },
    { id: "ma_15", question: "HCF of 24, 36, 40?", options: ["2", "4", "6", "12"], answer: "4", explanation: "Step 1: Factors of 24: 1, 2, 3, 4, 6, 8, 12, 24. Step 2: Factors of 36: 1, 2, 3, 4, 6, 9, 12, 18, 36. Step 3: Factors of 40: 1, 2, 4, 5, 8, 10, 20, 40. Step 4: Largest common is 4." },
    { id: "ma_16", question: "Ratio of side and diagonal of Square?", options: ["1:2", "1:√2", "2:1", "√2:1"], answer: "1:√2", explanation: "Step 1: Side = s. Step 2: Diagonal (using Pythagoras) = √(s^2+s^2) = s√2. Step 3: Ratio side:diagonal = s : s√2 = 1 : √2." },
    { id: "ma_17", question: "Median of 3, 5, 8, 1, 2, 4, 7?", options: ["3", "4", "5", "1"], answer: "4", explanation: "Step 1: Sort the numbers: 1, 2, 3, 4, 5, 7, 8. Step 2: Find the middle element. Step 3: 4 is in the center." },
    { id: "ma_18", question: "20% of A is 50. A is?", options: ["200", "250", "300", "500"], answer: "250", explanation: "Step 1: 0.20 * A = 50. Step 2: A = 50 / 0.20. Step 3: A = 500 / 2 = 250." },
    { id: "ma_19", question: "Product of two numbers is 120. HCF is 2. LCM is?", options: ["30", "60", "240", "120"], answer: "60", explanation: "Step 1: Property: HCF * LCM = Product of numbers. Step 2: 2 * LCM = 120. Step 3: LCM = 120 / 2 = 60." },
    { id: "ma_20", question: "A circle's circumference is 44. Area?", options: ["132", "154", "176", "198"], answer: "154", explanation: "Step 1: 2 * 22/7 * r = 44. Step 2: r = 7. Step 3: Area = 22/7 * 7^2 = 22 * 7 = 154." }
  ],

  English: [
    { id: "en_1", question: "Antonym of 'EPHEMERAL'?", options: ["Transient", "Permanent", "Weak", "Fast"], answer: "Permanent", explanation: "Ephemeral is short-lived." },
    { id: "en_2", question: "Synonym of 'ABATE'?", options: ["Increase", "Reduce", "Stabilize", "Free"], answer: "Reduce", explanation: "To abate is to become less intense or widespread." },
    { id: "en_3", question: "Choose correct: 'Either the boy or his parents ____ to blame.'", options: ["is", "are", "was", "has"], answer: "are", explanation: "Rule of proximity: verb agrees with the closer subject 'parents'." },
    { id: "en_4", question: "One word for 'A person who hates women'?", options: ["Misanthrope", "Misogynist", "Philanthropist", "Monogamist"], answer: "Misogynist", explanation: "Misogyny is the hatred of women." },
    { id: "en_5", question: "Meaning of 'To cry wolf'?", options: ["To shout", "False alarm", "Hunt", "Save"], answer: "False alarm", explanation: "Lying about danger when none exists." },
    { id: "en_6", question: "Correct spelling?", options: ["Occurence", "Occurrence", "Ocurence", "Occurance"], answer: "Occurrence", explanation: "Double c, double r, ends in -ence." },
    { id: "en_7", question: "Passive: 'I eat an apple.'", options: ["Apple is eaten by me.", "Apple was eaten by me.", "Apple is being eaten.", "Apple will be eaten."], answer: "Apple is eaten by me.", explanation: "Simple present passive." },
    { id: "en_8", question: "Plural of 'Thesis'?", options: ["Thesiss", "Theses", "Thesisa", "Thesisum"], answer: "Theses", explanation: "Bases on Greek rules." },
    { id: "en_9", question: "Idiom: 'Under the weather' means?", options: ["Fast", "Sick", "Flying", "Happy"], answer: "Sick", explanation: "Feeling unwell." },
    { id: "en_10", question: "Collective noun for Lions?", options: ["Herd", "Pride", "Pack", "School"], answer: "Pride", explanation: "A group of lions." },
    { id: "en_11", question: "Correct preposition: 'He is addicted ____ smoking.'", options: ["to", "with", "at", "by"], answer: "to", explanation: "Addicted is followed by 'to'." },
    { id: "en_12", question: "Synonym of 'PRECARIOUS'?", options: ["Stable", "Dangerous", "Strong", "Fast"], answer: "Dangerous", explanation: "Precarious means insecure or dangerously likely to fall." },
    { id: "en_13", question: "Antonym of 'ARROGANT'?", options: ["Proud", "Humble", "Smart", "Rich"], answer: "Humble", explanation: "Opposite of having too high an opinion of oneself." },
    { id: "en_14", question: "Choose the correct article: 'He is ____ honest man.'", options: ["a", "an", "the", "no article"], answer: "an", explanation: "'Honest' starts with a vowel sound (O)." },
    { id: "en_15", question: "Meaning of 'Couch Potato'?", options: ["Fit person", "Lazy person", "Cook", "Farmer"], answer: "Lazy person", explanation: "Someone who sits on the sofa all day." },
    { id: "en_16", question: "One word for 'A collection of poems'?", options: ["Library", "Anthology", "Archive", "Catalogue"], answer: "Anthology", explanation: "A published collection of poems or other pieces of writing." },
    { id: "en_17", question: "Identify error: 'Me and my friend went shopping.'", options: ["Me and my friend", "went", "shopping", "No error"], answer: "Me and my friend", explanation: "Should be 'My friend and I'." },
    { id: "en_18", question: "Synonym of 'ZENITH'?", options: ["Lower", "Peak", "Middle", "End"], answer: "Peak", explanation: "The highest point." },
    { id: "en_19", question: "Fill in: 'I ____ finished my work yet.'", options: ["haven't", "didn't", "hasn't", "wasn't"], answer: "haven't", explanation: "Present perfect for unfinished past action." },
    { id: "en_20", question: "Plural of 'Index'?", options: ["Indexies", "Indices", "Indexs", "Indea"], answer: "Indices", explanation: "Indices is the standard plural form." }
  ]
};
